'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { auth } from '@/lib/firebase';

type Q = { id:string; stem:string; options:{id:string;text:string}[]; correct:string; explanation:string; sources:{title:string;url:string}[]; condition:string; domain:string; hidden:boolean };
export default function BancoRepasoPage() {
  const { user, loading } = useAuth(); const [items,setItems]=useState<Q[]>([]); const [query,setQuery]=useState(''); const [zone,setZone]=useState('all'); const [busy,setBusy]=useState<string>(); const [error,setError]=useState('');
  const headers = async (json = false) => { const token = await auth.currentUser?.getIdToken(); if (!token) throw Error('No se pudo validar tu sesión docente. Recarga la página.'); return { Authorization:`Bearer ${token}`, ...(json ? {'Content-Type':'application/json'} : {}) }; };
  useEffect(()=>{ if(user?.role==='DOCENTE') (async()=>{ try { const r=await fetch('/api/repaso-msk/bank',{headers:await headers(),cache:'no-store'}); if(!r.ok) throw Error('No se pudo cargar el banco docente.'); const x=await r.json(); setItems(x.questions); } catch(e) { setError(e instanceof Error?e.message:'No se pudo cargar el banco docente.'); } })(); },[user]);
  const shown=useMemo(()=>items.filter(q=>(zone==='all'||q.id.startsWith(zone))&&`${q.stem} ${q.condition} ${q.id}`.toLowerCase().includes(query.toLowerCase())),[items,zone,query]);
  const toggle=async(q:Q)=>{setBusy(q.id); try { const r=await fetch('/api/repaso-msk/bank',{method:'PATCH',headers:await headers(true),body:JSON.stringify({id:q.id,hidden:!q.hidden})}); if(!r.ok) throw Error('No se pudo actualizar el ítem.'); setItems(a=>a.map(x=>x.id===q.id?{...x,hidden:!x.hidden}:x)); } catch(e) { setError(e instanceof Error?e.message:'No se pudo actualizar el ítem.'); } finally {setBusy(undefined);} };
  if(loading) return <p className="p-8">Verificando acceso…</p>;
  if(user?.role!=='DOCENTE') return <section className="mx-auto max-w-lg p-8 text-center"><h1 className="text-2xl font-bold">Solo docente</h1><p className="mt-3 text-slate-600">El banco y sus respuestas no están disponibles para internos.</p></section>;
  return <main className="mx-auto max-w-5xl p-4 sm:p-8"><Link href="/app/repaso-msk" className="text-sm font-bold text-indigo-700">← Volver al repaso</Link><div className="mt-4 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold tracking-widest text-indigo-300">PANEL DOCENTE</p><h1 className="mt-1 text-2xl font-bold">Banco de preguntas MSK</h1><p className="mt-2 text-sm text-slate-300">Las 315 preguntas se muestran completas por defecto. Buscar y filtrar son opcionales. Desactivar no borra historial.</p></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filtro opcional" className="min-h-11 flex-1 rounded-xl border p-3"/><select value={zone} onChange={e=>setZone(e.target.value)} className="min-h-11 rounded-xl border p-3"><option value="all">Las tres zonas (315)</option><option value="knee">Rodilla</option><option value="hip">Cadera e ingle</option><option value="shoulder">Hombro</option></select></div>{error&&<p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<p className="mt-4 text-sm text-slate-600">{shown.length} ítems mostrados · {items.filter(q=>q.hidden).length} desactivados</p><section className="mt-3 space-y-4">{shown.map(q=><article key={q.id} className={`rounded-2xl border p-4 shadow-sm ${q.hidden?'bg-slate-50 opacity-70':'bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-indigo-700">{q.id} · {q.condition} · {q.domain}</p><h2 className="mt-2 font-semibold">{q.stem}</h2></div><button disabled={busy===q.id} onClick={()=>toggle(q)} className="rounded-lg border px-3 py-2 text-sm font-bold">{q.hidden?'Reactivar':'Desactivar'}</button></div><ol className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map(o=><li key={o.id} className={`rounded-lg p-2 text-sm ${o.id===q.correct?'bg-emerald-100 font-semibold text-emerald-900':'bg-slate-50'}`}>{o.id}. {o.text}{o.id===q.correct?' ✓':''}</li>)}</ol><div className="mt-3 rounded-lg bg-indigo-50 p-3 text-sm"><b>Fundamento:</b> {q.explanation}</div><p className="mt-2 text-xs">{q.sources.map(s=><a className="mr-3 text-indigo-700 underline" target="_blank" key={s.url} href={s.url}>{s.title}</a>)}</p></article>)}</section></main>;
}
